server:
  port: 80
spring:
  security:
    user:
      name: gedehua
      password: 2002726+abc
  datasource:
    password: 2002726+abc
    url: jdbc:mysql://localhost:3306/db1?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: gedehua

